version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    volumes:
      - $PWD/data:/qdrant/storage
    networks:
      macnet:
        ipv4_address: 192.168.50.16
    
networks:
  macnet:
    external: true

# this is an example which using macnet